// Completion E2E fixture for the isolated dispatch prototype. Google/Cesium rendering is fixture-backed.
import { chromium } from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import http from 'node:http';import path from 'node:path';import { fileURLToPath } from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));const server=http.createServer(async(req,res)=>{const pathname=decodeURIComponent(new URL(req.url,'http://localhost').pathname);const file=path.resolve(root,`.${pathname==='/'?'/dispatch-prototype-v0.0.40.html':pathname}`);if(!file.startsWith(root))return res.writeHead(403).end();try{const body=await fs.readFile(file);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.geojson':'application/geo+json','.glb':'model/gltf-binary'})[path.extname(file)]||'application/octet-stream');res.end(body)}catch{res.writeHead(404).end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/dispatch-prototype-v0.0.40.html`;const browser=await chromium.launch({headless:true});
function fixture(){const C=window.Cesium={...window.Cesium};const Original=C.Viewer;C.Viewer=function(...args){const viewer=window.testViewer=new Original(...args);viewer.scene.sampleHeight=()=>190;return viewer};C.createGooglePhotorealistic3DTileset=async(_key,options)=>{if(!options?.showCreditsOnScreen)throw Error('Missing Google attribution');window.testCreditsEnabled=true;const tiles=new C.PrimitiveCollection();tiles.tilesLoaded=true;tiles.tileFailed=new C.Event();tiles.allTilesLoaded=new C.Event();return tiles}}
async function setup(viewport={width:1440,height:900}){const context=await browser.newContext({viewport,hasTouch:viewport.width<600});const page=await context.newPage();const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/app-v0.0.8.js?v=0.0.8',async route=>{const response=await route.fetch();await route.fulfill({response,body:`(${fixture.toString()})();\n${await response.text()}`})});await page.route('https://tile.openstreetmap.org/**',r=>r.fulfill({status:200,contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2nXQAAAAASUVORK5CYII=','base64')}));await page.goto(url);await page.waitForFunction(()=>window.__CITY_DEMO_RUNTIME__&&window.__DISPATCH_MODE_RUNTIME__&&window.__DISPATCH_GAMEPLAY__&&window.__DISPATCH_EMS_TRANSPORT__&&window.__DISPATCH_TABLET__&&window.__DISPATCH_AFTER_ACTION__);await page.locator('#api-key').fill('fixture-not-a-real-key');await page.locator('#launch-button').click();await page.waitForFunction(()=>window.__CITY_DEMO_RUNTIME__.snapshot().pickerActive);return{context,page,errors}}
async function choosePeterborough(page){for(let i=0;i<12&&(await page.locator('#city-picker-name').innerText()).trim()!=='Peterborough';i++)await page.keyboard.press('ArrowRight');assert.equal((await page.locator('#city-picker-name').innerText()).trim(),'Peterborough')}
async function launchBase(page,service,index){await choosePeterborough(page);await page.waitForSelector('#dispatch-launch-direct:not([hidden])');await page.locator('#dispatch-launch-direct').click();await page.waitForSelector('#dispatch-mode-overlay:not([hidden])');await page.locator('[data-mode="dispatch"]').click();await page.locator(`[data-service="${service}"]`).click();const bases=page.locator('[data-base]');assert.ok(await bases.count()>=(service==='fire'?3:2));const expected=await bases.nth(index).getAttribute('data-base');await bases.nth(index).click();await page.waitForFunction(id=>window.__DISPATCH_MODE_RUNTIME__.snapshot().baseId===id,expected);await page.waitForFunction(()=>window.__CITY_DEMO_RUNTIME__.snapshot().running);return page.evaluate(()=>({mode:window.__DISPATCH_MODE_RUNTIME__.snapshot(),vehicle:window.__CITY_DEMO_RUNTIME__.snapshot().vehicle}))}
try{
 for(const [service,count] of [['fire',3],['ems',2]])for(let i=0;i<count;i++){const run=await setup();const s=await launchBase(run.page,service,i);assert.equal(s.mode.service,service);assert.ok(Number.isFinite(s.vehicle.lat)&&Number.isFinite(s.vehicle.lon));assert.ok(Math.abs(s.vehicle.lat-Number(s.mode.base.spawnLat))<.00001);assert.ok(Math.abs(s.vehicle.lon-Number(s.mode.base.spawnLng))<.00001);assert.deepEqual(run.errors,[]);await run.context.close()}
 const fire=await setup();await launchBase(fire.page,'fire',0);assert.equal(await fire.page.evaluate(()=>window.testCreditsEnabled),true);await fire.page.evaluate(()=>window.__DISPATCH_GAMEPLAY__.startCall());await fire.page.waitForFunction(()=>window.__DISPATCH_GAMEPLAY__.snapshot().state==='ENROUTE');assert.ok((await fire.page.evaluate(()=>window.__DISPATCH_GAMEPLAY__.snapshot())).eligibleCount>0);await fire.page.evaluate(()=>window.__DISPATCH_TABLET__.open());await fire.page.waitForFunction(()=>window.__DISPATCH_TABLET__.snapshot().hasMap);await fire.page.evaluate(()=>window.__DISPATCH_GAMEPLAY__.markOnScene());await fire.page.evaluate(()=>window.__DISPATCH_GAMEPLAY__.clearCall());await fire.page.waitForFunction(()=>window.__DISPATCH_AFTER_ACTION__.snapshot().reviewing);assert.equal((await fire.page.evaluate(()=>window.__DISPATCH_AFTER_ACTION__.snapshot())).historyCount,1);assert.deepEqual(fire.errors,[]);await fire.context.close();
 const ems=await setup();await launchBase(ems.page,'ems',0);await ems.page.evaluate(()=>window.__DISPATCH_GAMEPLAY__.startCall());await ems.page.waitForFunction(()=>window.__DISPATCH_GAMEPLAY__.snapshot().state==='ENROUTE');await ems.page.evaluate(()=>window.__DISPATCH_GAMEPLAY__.markOnScene());await ems.page.waitForFunction(()=>window.__DISPATCH_EMS_TRANSPORT__.snapshot().phase==='TRANSPORTING',{timeout:5000});const hospital=await ems.page.evaluate(()=>window.__DISPATCH_EMS_TRANSPORT__.snapshot().hospital);await ems.page.evaluate(h=>window.__CITY_DEMO_RUNTIME__.spawnAtCoordinates({id:'prhc-test',name:'PRHC',lat:Number(h.checkpointLat),lon:Number(h.checkpointLng),headingDeg:0}),hospital);await ems.page.waitForFunction(()=>window.__DISPATCH_EMS_TRANSPORT__.snapshot().phase==='COMPLETE',{timeout:5000});assert.ok((await ems.page.evaluate(()=>window.__DISPATCH_EMS_TRANSPORT__.snapshot())).transportMs>=0);assert.deepEqual(ems.errors,[]);await ems.context.close();
 const mobile=await setup({width:390,height:844});await launchBase(mobile.page,'fire',0);assert.equal(await mobile.page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert.deepEqual(mobile.errors,[]);await mobile.context.close();
 console.log(JSON.stringify({allFireBases:true,allEmsBases:true,fireLifecycle:true,emsHospitalLifecycle:true,tablet:true,review:true,mobile:true,googleAttribution:true},null,2));
}finally{await browser.close();await new Promise(r=>server.close(r))}