// Completion E2E fixture for isolated dispatch v0.0.43. Google rendering is fixture-backed.
import { chromium } from 'playwright';import assert from 'node:assert/strict';import fs from 'node:fs/promises';import http from 'node:http';import path from 'node:path';import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('../',import.meta.url));
function fixture(){const C=window.Cesium={...window.Cesium};const Original=C.Viewer;C.Viewer=function(...args){const viewer=window.testViewer=new Original(...args);viewer.scene.sampleHeight=()=>190;viewer.scene.sampleHeightMostDetailed=async points=>points.map(p=>{p.height=190;return p});return viewer};C.createGooglePhotorealistic3DTileset=async(_key,options)=>{if(!options?.showCreditsOnScreen)throw Error('Missing Google attribution');window.testCreditsEnabled=true;const tiles=new C.PrimitiveCollection();tiles.tilesLoaded=true;tiles.tileFailed=new C.Event();tiles.allTilesLoaded=new C.Event();return tiles}}
const server=http.createServer(async(req,res)=>{const p=decodeURIComponent(new URL(req.url,'http://localhost').pathname),f=path.resolve(root,`.${p==='/'?'/dispatch.html':p}`);if(!f.startsWith(root))return res.writeHead(403).end();try{const b=await fs.readFile(f);res.setHeader('Content-Type',({'.html':'text/html','.js':'text/javascript','.css':'text/css','.geojson':'application/geo+json','.glb':'model/gltf-binary'})[path.extname(f)]||'application/octet-stream');res.end(b)}catch{res.writeHead(404).end()}});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url=`http://127.0.0.1:${server.address().port}/dispatch.html`;const browser=await chromium.launch({headless:true});
async function setup(viewport={width:1440,height:900}){const context=await browser.newContext({viewport,hasTouch:viewport.width<600});const page=await context.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/app-dispatch-runtime-v0.0.43.js?v=0.0.43',async route=>{const response=await route.fetch();await route.fulfill({response,body:`(${fixture.toString()})();\n${await response.text()}`})});await page.route('https://tile.openstreetmap.org/**',r=>r.fulfill({status:200,contentType:'image/png',body:Buffer.from('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mP8/x8AAusB9Wl2nXQAAAAASUVORK5CYII=','base64')}));await page.goto(url);await page.waitForFunction(()=>window.__CITY_DEMO_RUNTIME__&&window.__DISPATCH_MODE_RUNTIME__&&window.__DISPATCH_GAMEPLAY__&&window.__DISPATCH_EMS_TRANSPORT__&&window.__DISPATCH_TABLET__&&window.__DISPATCH_AFTER_ACTION__);await page.locator('#api-key').fill('fixture-not-a-real-key');await page.locator('#launch-button').click();await page.waitForFunction(()=>window.__CITY_DEMO_RUNTIME__.snapshot().pickerActive);return{context,page,errors}}
async function launchBase(page,service,index){
  assert.equal((await page.locator('#city-picker-name').innerText()).trim(),'Peterborough');
  const bases=await page.evaluate(s=>window.__DISPATCH_MODE_RUNTIME__.bases(s),service);
  assert.ok(bases.length>=(service==='fire'?3:2));
  const expected=bases[index].id;
  await page.evaluate(({service,id})=>window.__DISPATCH_MODE_RUNTIME__.launchBase(service,id),{service,id:expected});
  await page.waitForFunction(id=>window.__DISPATCH_MODE_RUNTIME__.snapshot().baseId===id,expected);
  await page.waitForFunction(()=>window.__CITY_DEMO_RUNTIME__.snapshot().running);
  return page.evaluate(()=>({mode:window.__DISPATCH_MODE_RUNTIME__.snapshot(),runtime:window.__CITY_DEMO_RUNTIME__.snapshot(),vehicle:window.__CITY_DEMO_RUNTIME__.snapshot().vehicle}));
}
try{for(const [service,count] of [['fire',3],['ems',2]])for(let i=0;i<count;i++){const r=await setup(),s=await launchBase(r.page,service,i);assert.equal(s.mode.service,service);assert.equal(s.runtime.dispatchGroundLocked,true);assert.equal(s.runtime.dispatchGroundHeight,190);assert.ok(Math.abs(s.vehicle.lat-Number(s.mode.base.spawnLat))<.00001);assert.ok(Math.abs(s.vehicle.lon-Number(s.mode.base.spawnLng))<.00001);assert.deepEqual(r.errors,[]);await r.context.close()}
const fire=await setup();await launchBase(fire.page,'fire',0);await fire.page.evaluate(()=>window.__DISPATCH_GAMEPLAY__.startCall());await fire.page.waitForFunction(()=>window.__DISPATCH_GAMEPLAY__.snapshot().state==='ENROUTE');assert.ok((await fire.page.evaluate(()=>window.__DISPATCH_GAMEPLAY__.snapshot())).eligibleCount>0);await fire.page.evaluate(()=>window.__DISPATCH_TABLET__.open());await fire.page.waitForFunction(()=>window.__DISPATCH_TABLET__.snapshot().hasMap);await fire.page.evaluate(()=>window.__DISPATCH_GAMEPLAY__.markOnScene());await fire.page.evaluate(()=>window.__DISPATCH_GAMEPLAY__.clearCall());await fire.page.waitForFunction(()=>window.__DISPATCH_AFTER_ACTION__.snapshot().reviewing);assert.equal((await fire.page.evaluate(()=>window.__DISPATCH_AFTER_ACTION__.snapshot())).historyCount,1);await fire.context.close();
const ems=await setup();await launchBase(ems.page,'ems',0);await ems.page.evaluate(()=>window.__DISPATCH_GAMEPLAY__.startCall());await ems.page.waitForFunction(()=>window.__DISPATCH_GAMEPLAY__.snapshot().state==='ENROUTE');await ems.page.evaluate(()=>window.__DISPATCH_GAMEPLAY__.markOnScene());await ems.page.waitForFunction(()=>window.__DISPATCH_EMS_TRANSPORT__.snapshot().phase==='TRANSPORTING',{timeout:5000});const h=await ems.page.evaluate(()=>window.__DISPATCH_EMS_TRANSPORT__.snapshot().hospital);await ems.page.evaluate(x=>window.__CITY_DEMO_RUNTIME__.spawnAtCoordinates({id:'prhc-test',name:'PRHC',lat:+x.checkpointLat,lon:+x.checkpointLng,headingDeg:0}),h);await ems.page.waitForFunction(()=>window.__DISPATCH_EMS_TRANSPORT__.snapshot().phase==='COMPLETE',{timeout:5000});await ems.context.close();
const mobile=await setup({width:390,height:844});await launchBase(mobile.page,'fire',0);assert.equal(await mobile.page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await mobile.context.close();console.log(JSON.stringify({allFireBases:true,allEmsBases:true,fireLifecycle:true,emsHospitalLifecycle:true,tablet:true,review:true,mobile:true},null,2))}finally{await browser.close();await new Promise(r=>server.close(r))}