// Stage 7: sampled driven-path history and Cesium after-action route review.
const VERSION='0.0.17';
const data=await window.DISPATCH_PROTOTYPE?.cityDataReady;
if(!data) throw new Error('Dispatch data unavailable for after-action review.');
const runtime=()=>window.__CITY_DEMO_RUNTIME__;
const gameplay=()=>window.__DISPATCH_GAMEPLAY__?.snapshot?.()||{};
const mode=()=>window.__DISPATCH_MODE_RUNTIME__?.snapshot?.()||{};
const ems=()=>window.__DISPATCH_EMS_TRANSPORT__?.snapshot?.()||{};
const rad=n=>n*Math.PI/180;
const distance=(a,b)=>{const R=6371000,p1=rad(a.lat),p2=rad(b.lat),dp=rad(b.lat-a.lat),dl=rad(b.lng-a.lng);const x=Math.sin(dp/2)**2+Math.cos(p1)*Math.cos(p2)*Math.sin(dl/2)**2;return 2*R*Math.atan2(Math.sqrt(x),Math.sqrt(1-x));};
const pathDistance=p=>p.slice(1).reduce((n,x,i)=>n+distance(p[i],x),0);
let mission=null,reviewEntities=[],reviewing=false,graphPromise=null;
const histories=[];
function point(){const v=runtime()?.snapshot?.().vehicle,lat=Number(v?.lat),lng=Number(v?.lon);return Number.isFinite(lat)&&Number.isFinite(lng)?{lat,lng,t:performance.now()}:null;}
function sample(){if(!mission||reviewing)return;const p=point();if(!p)return;const leg=mission.legs.at(-1);if(!leg)return;const prev=leg.actual.at(-1);if(!prev||distance(prev,p)>=8||p.t-prev.t>=2500)leg.actual.push(p);}
async function graph(){if(graphPromise)return graphPromise;graphPromise=fetch(data.roads.dataUrl).then(r=>{if(!r.ok)throw Error(`Road graph ${r.status}`);return r.json();}).then(g=>{const nodes=[],byKey=new Map(),edges=new Map(),key=(a,b)=>`${a.toFixed(6)},${b.toFixed(6)}`;const node=(lat,lng)=>{const k=key(lat,lng);if(byKey.has(k))return byKey.get(k);const n={key:k,lat,lng};nodes.push(n);byKey.set(k,n);edges.set(k,[]);return n;};for(const f of g.features||[]){const lines=f.geometry?.type==='LineString'?[f.geometry.coordinates]:f.geometry?.type==='MultiLineString'?f.geometry.coordinates:[];for(const line of lines)for(let i=1;i<line.length;i++){const a=node(+line[i-1][1],+line[i-1][0]),b=node(+line[i][1],+line[i][0]),w=distance(a,b);edges.get(a.key).push([b,w]);edges.get(b.key).push([a,w]);}}return {nodes,edges};});return graphPromise;}
async function recommended(a,b){const g=await graph(),nearest=p=>g.nodes.reduce((best,n)=>!best||distance(p,n)<distance(p,best)?n:best,null),s=nearest(a),t=nearest(b);if(!s||!t)return [a,b];const d=new Map([[s.key,0]]),prev=new Map(),q=[s];while(q.length){q.sort((x,y)=>(d.get(x.key)??Infinity)-(d.get(y.key)??Infinity));const u=q.shift();if(u.key===t.key)break;for(const [v,w] of g.edges.get(u.key)||[]){const nd=d.get(u.key)+w;if(nd<(d.get(v.key)??Infinity)){d.set(v.key,nd);prev.set(v.key,u);if(!q.includes(v))q.push(v);}}}const out=[];for(let c=t;c;c=prev.get(c.key)){out.push({lat:c.lat,lng:c.lng});if(c.key===s.key)break;}out.reverse();return out.length>1?[a,...out,b]:[a,b];}
function begin(call){const p=point();if(!p)return;mission={id:`${Date.now()}-${call.id}`,service:mode().service,call,baseId:mode().baseId,startedAt:Date.now(),responseMs:0,transportMs:0,legs:[{kind:'response',start:p,end:{lat:+call.lat,lng:+call.lng},actual:[p],recommended:[]}]};}
async function finalizeLeg(leg){const p=point();if(p&&(!leg.actual.length||distance(leg.actual.at(-1),p)>1))leg.actual.push(p);leg.recommended=await recommended(leg.start,leg.end);leg.actualMeters=pathDistance(leg.actual);leg.recommendedMeters=pathDistance(leg.recommended);}
async function onScene(e){if(!mission)return;mission.responseMs=+e.detail.responseMs||0;await finalizeLeg(mission.legs[0]);if(mission.service==='ems'){const p=point()||mission.legs[0].end,h=data.hospital;mission.legs.push({kind:'transport',start:p,end:{lat:+h.checkpointLat,lng:+h.checkpointLng},actual:[p],recommended:[]});}}
async function complete(){if(!mission)return;if(mission.service==='ems'){mission.transportMs=+ems().transportMs||0;await finalizeLeg(mission.legs[1]);}mission.completedAt=Date.now();histories.push(structuredClone(mission));showReview();}
function clearEntities(){const v=runtime()?.getViewer?.();if(v)for(const e of reviewEntities)v.entities.remove(e);reviewEntities=[];}
function showReview(){if(!mission)return;const v=runtime()?.getViewer?.(),C=window.Cesium;if(!v||!C)return;clearEntities();reviewing=true;for(const leg of mission.legs){if(leg.actual.length>1)reviewEntities.push(v.entities.add({polyline:{positions:leg.actual.map(p=>C.Cartesian3.fromDegrees(p.lng,p.lat,5)),width:5,material:C.Color.CYAN.withAlpha(.8),clampToGround:true}}));if(leg.recommended.length>1)reviewEntities.push(v.entities.add({polyline:{positions:leg.recommended.map(p=>C.Cartesian3.fromDegrees(p.lng,p.lat,7)),width:4,material:C.Color.LIME.withAlpha(.7),clampToGround:true}}));}const pts=mission.legs.flatMap(l=>[...l.actual,...l.recommended]);if(pts.length){const west=Math.min(...pts.map(p=>p.lng)),east=Math.max(...pts.map(p=>p.lng)),south=Math.min(...pts.map(p=>p.lat)),north=Math.max(...pts.map(p=>p.lat));v.camera.flyTo({destination:C.Rectangle.fromDegrees(west-.002,south-.002,east+.002,north+.002),duration:1.2});}renderPanel();}
function exitReview(){reviewing=false;clearEntities();panel.hidden=true;}
const style=document.createElement('style');style.textContent=`#dispatch-review{position:fixed;z-index:9300;left:14px;top:14px;max-width:320px;background:#07131ded;color:#eef9ff;border:1px solid #5cc7ff66;border-radius:13px;padding:12px;font:12px system-ui;box-shadow:0 12px 40px #0008}#dispatch-review[hidden]{display:none}#dispatch-review strong{font-size:14px}.review-leg{margin-top:7px;color:#bfe9ff}.review-legend{margin-top:8px}.review-legend span{margin-right:12px}.review-close{margin-top:10px;border:1px solid #5cc7ff;border-radius:8px;background:#0b4868;color:#fff;padding:7px 11px;font-weight:700}@media(max-width:600px){#dispatch-review{top:auto;bottom:112px;left:8px;right:8px;max-width:none}}`;document.head.append(style);
const panel=document.createElement('aside');panel.id='dispatch-review';panel.hidden=true;document.body.append(panel);
function renderPanel(){if(!mission)return;panel.hidden=false;const legs=mission.legs.map(l=>`<div class="review-leg">${l.kind==='response'?'Response':'Transport'}: actual ${(l.actualMeters/1000).toFixed(2)} km · recommended ${(l.recommendedMeters/1000).toFixed(2)} km</div>`).join('');panel.innerHTML=`<strong>After-Action Review</strong>${legs}<div class="review-leg">Response ${(mission.responseMs/1000).toFixed(0)}s${mission.service==='ems'?` · Transport ${(mission.transportMs/1000).toFixed(0)}s`:''}</div><div class="review-legend"><span>● Actual</span><span>● Recommended</span></div><button class="review-close">Return to truck</button>`;panel.querySelector('.review-close').onclick=exitReview;}
window.addEventListener('dispatch-call-started',e=>{exitReview();begin(e.detail.call);});
window.addEventListener('dispatch-call-onscene',onScene);
window.addEventListener('dispatch-call-cleared',()=>{if(mission?.service==='fire')complete();});
window.addEventListener('dispatch-ems-complete',complete);
window.addEventListener('dispatch-base-selected',()=>{exitReview();mission=null;});window.addEventListener('city-session-reset',()=>{exitReview();mission=null;});
setInterval(sample,750);
window.__DISPATCH_AFTER_ACTION__=Object.freeze({version:VERSION,snapshot:()=>({version:VERSION,reviewing,mission:mission?structuredClone(mission):null,historyCount:histories.length}),history:()=>structuredClone(histories),showReview,exitReview});
