// Stage 6: responsive MDT/tablet with live apparatus position and independent OSM-road route guidance.
const VERSION='0.0.16';
const data=await window.DISPATCH_PROTOTYPE?.cityDataReady;
if(!data) throw new Error('Dispatch data unavailable for response tablet.');
const gameplay=()=>window.__DISPATCH_GAMEPLAY__?.snapshot?.()||{};
const mode=()=>window.__DISPATCH_MODE_RUNTIME__?.snapshot?.()||{};
const vehicle=()=>window.__CITY_DEMO_RUNTIME__?.snapshot?.().vehicle||null;
let open=false,map=null,truckMarker=null,destMarker=null,routeLine=null,graphPromise=null,lastKey='';
function destination(){const g=gameplay();if(!g.call)return null;const ems=window.__EMS_TRANSPORT__?.snapshot?.();if(ems?.phase==='TRANSPORTING'){return {lat:Number(data.hospital.checkpointLat),lng:Number(data.hospital.checkpointLng),name:data.hospital.name||'PRHC',address:data.hospital.address||'Hospital drop-off'};}return {lat:Number(g.call.lat),lng:Number(g.call.lng),name:g.call.name,address:g.call.addr};}
function nearest(nodes,p){let best=null,bd=Infinity;for(const n of nodes){const d=(n.lat-p.lat)**2+(n.lng-p.lng)**2;if(d<bd){bd=d;best=n;}}return best;}
async function graph(){if(graphPromise)return graphPromise;graphPromise=fetch(data.roads.dataUrl).then(r=>{if(!r.ok)throw new Error(`Road graph ${r.status}`);return r.json();}).then(g=>{const nodes=[],edges=new Map();const key=(lat,lng)=>`${lat.toFixed(6)},${lng.toFixed(6)}`;const node=(lat,lng)=>{const k=key(lat,lng);let n=nodes.find(x=>x.key===k);if(!n){n={key:k,lat,lng};nodes.push(n);edges.set(k,[]);}return n;};for(const f of g.features||[]){const lines=f.geometry?.type==='LineString'?[f.geometry.coordinates]:f.geometry?.type==='MultiLineString'?f.geometry.coordinates:[];for(const line of lines){for(let i=1;i<line.length;i++){const a=node(Number(line[i-1][1]),Number(line[i-1][0])),b=node(Number(line[i][1]),Number(line[i][0]));const w=Math.hypot(a.lat-b.lat,a.lng-b.lng);edges.get(a.key).push([b,w]);edges.get(b.key).push([a,w]);}}}return {nodes,edges};});return graphPromise;}
async function route(a,b){const g=await graph(),s=nearest(g.nodes,a),t=nearest(g.nodes,b);if(!s||!t)return [[a.lat,a.lng],[b.lat,b.lng]];const dist=new Map([[s.key,0]]),prev=new Map(),q=[s];while(q.length){q.sort((x,y)=>(dist.get(x.key)||Infinity)-(dist.get(y.key)||Infinity));const u=q.shift();if(u.key===t.key)break;for(const [v,w] of g.edges.get(u.key)||[]){const nd=(dist.get(u.key)||0)+w;if(nd<(dist.get(v.key)??Infinity)){dist.set(v.key,nd);prev.set(v.key,u);if(!q.some(x=>x.key===v.key))q.push(v);}}}const out=[];let cur=t;while(cur){out.push([cur.lat,cur.lng]);if(cur.key===s.key)break;cur=prev.get(cur.key);}out.reverse();return out.length>1?out:[[a.lat,a.lng],[b.lat,b.lng]];}
const css=document.createElement('style');css.textContent=`#dispatch-tablet-open{position:fixed;z-index:8750;right:14px;bottom:70px;border:1px solid #5cc7ff;border-radius:10px;padding:9px 12px;background:#0b4868;color:white;font:800 11px system-ui;cursor:pointer}#dispatch-tablet[hidden]{display:none}#dispatch-tablet{position:fixed;z-index:9900;inset:5vh 6vw;display:grid;grid-template-rows:auto 1fr;background:#0a1421;border:7px solid #07101a;border-radius:22px;box-shadow:0 25px 90px #000b;color:white;overflow:hidden;font-family:system-ui}.mdt-head{display:flex;align-items:center;gap:10px;padding:12px 14px;background:#12253a}.mdt-head div{flex:1}.mdt-head strong,.mdt-head span{display:block}.mdt-head span{font-size:11px;color:#b9cfdd;margin-top:2px}.mdt-close{border:1px solid #ffffff33;border-radius:9px;background:#26384a;color:white;width:40px;height:40px;font-size:22px}.mdt-map{min-height:0}.mdt-map .leaflet-control-attribution{font-size:8px}@media(max-width:650px){#dispatch-tablet{inset:5px;border-width:4px;border-radius:14px}#dispatch-tablet-open{right:8px;bottom:112px}.mdt-head{padding:9px}.mdt-head strong{font-size:13px}.mdt-head span{font-size:10px}}`;document.head.append(css);
const button=document.createElement('button');button.id='dispatch-tablet-open';button.textContent='Dispatch Tablet';button.hidden=true;document.body.append(button);
const shell=document.createElement('section');shell.id='dispatch-tablet';shell.hidden=true;shell.innerHTML=`<header class="mdt-head"><div><strong id="mdt-title">Dispatch Tablet</strong><span id="mdt-address">No active destination</span></div><button class="mdt-close" aria-label="Close tablet">×</button></header><div id="mdt-map" class="mdt-map"></div>`;document.body.append(shell);
async function leaflet(){if(window.L)return;if(!document.querySelector('link[data-mdt-leaflet]')){const l=document.createElement('link');l.rel='stylesheet';l.href='https://unpkg.com/leaflet@1.9.4/dist/leaflet.css';l.dataset.mdtLeaflet='1';document.head.append(l);}await new Promise((res,rej)=>{const s=document.createElement('script');s.src='https://unpkg.com/leaflet@1.9.4/dist/leaflet.js';s.onload=res;s.onerror=rej;document.head.append(s);});}
async function ensureMap(){await leaflet();if(map)return;map=L.map('mdt-map',{zoomControl:true}).setView([44.309,-78.319],13);L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:'© OpenStreetMap contributors'}).addTo(map);}
async function refresh(force=false){const m=mode(),g=gameplay(),v=vehicle(),d=destination();button.hidden=!(m.mode==='dispatch'&&m.baseId&&g.call);if(!open||!d||!v)return;await ensureMap();const p={lat:Number(v.lat),lng:Number(v.lon)};if(!Number.isFinite(p.lat)||!Number.isFinite(p.lng))return;truckMarker?truckMarker.setLatLng([p.lat,p.lng]):truckMarker=L.circleMarker([p.lat,p.lng],{radius:7}).addTo(map).bindTooltip('Apparatus');destMarker?destMarker.setLatLng([d.lat,d.lng]):destMarker=L.circleMarker([d.lat,d.lng],{radius:9}).addTo(map).bindTooltip('Destination');shell.querySelector('#mdt-title').textContent=d.name||'Active incident';shell.querySelector('#mdt-address').textContent=d.address||'Route destination';const key=`${d.lat.toFixed(5)},${d.lng.toFixed(5)}|${p.lat.toFixed(4)},${p.lng.toFixed(4)}`;if(force||key!==lastKey){lastKey=key;try{const pts=await route(p,d);if(routeLine)routeLine.remove();routeLine=L.polyline(pts,{weight:5,opacity:.75}).addTo(map);map.fitBounds(L.latLngBounds([[p.lat,p.lng],[d.lat,d.lng]]).pad(.18),{animate:false});}catch(e){console.warn('[Dispatch tablet] route fallback',e);if(routeLine)routeLine.remove();routeLine=L.polyline([[p.lat,p.lng],[d.lat,d.lng]],{weight:4,dashArray:'8 8'}).addTo(map);}}}
button.onclick=async()=>{open=true;shell.hidden=false;await refresh(true);setTimeout(()=>map?.invalidateSize(),30);};shell.querySelector('.mdt-close').onclick=()=>{open=false;shell.hidden=true;};window.addEventListener('dispatch-call-started',()=>setTimeout(()=>refresh(true),0));window.addEventListener('dispatch-call-cleared',()=>{button.hidden=true;open=false;shell.hidden=true;});window.addEventListener('city-session-reset',()=>{button.hidden=true;open=false;shell.hidden=true;});setInterval(()=>refresh(false),1000);
window.__DISPATCH_TABLET__=Object.freeze({version:VERSION,open:()=>button.click(),close:()=>shell.querySelector('.mdt-close').click(),snapshot:()=>({version:VERSION,open,destination:destination(),hasMap:Boolean(map),hasRoute:Boolean(routeLine)})});
